android/app/build.gradle.kts
#35 
<br>
- android targetSDK를 35에서 36으로 변경했습니다.
=> [AN] Andoid TargetSDK 변경

backend/src/main/java/com/daedan/festabook/place/controller/PlaceController.java, backend/src/main/java/com/daedan/festabook/place/domain/Place.java, backend/src/main/java/com/daedan/festabook/place/domain/PlaceAnnouncement.java, backend/src/main/java/com/daedan/festabook/place/domain/PlaceCategory.java, backend/src/main/java/com/daedan/festabook/place/domain/PlaceImage.java, backend/src/main/java/com/daedan/festabook/place/dto/PlaceAnnouncementResponse.java, backend/src/main/java/com/daedan/festabook/place/dto/PlaceAnnouncementResponses.java, backend/src/main/java/com/daedan/festabook/place/dto/PlaceImageResponse.java, backend/src/main/java/com/daedan/festabook/place/dto/PlaceImageResponses.java, backend/src/main/java/com/daedan/festabook/place/dto/PlaceRequest.java, backend/src/main/java/com/daedan/festabook/place/dto/PlaceResponse.java, backend/src/main/java/com/daedan/festabook/place/dto/PlaceResponses.java, backend/src/main/java/com/daedan/festabook/place/infrastructure/PlaceAnnouncementJpaRepository.java, backend/src/main/java/com/daedan/festabook/place/infrastructure/PlaceImageJpaRepository.java, backend/src/main/java/com/daedan/festabook/place/infrastructure/PlaceJpaRepository.java, backend/src/main/java/com/daedan/festabook/place/service/PlaceAnnouncementService.java, backend/src/main/java/com/daedan/festabook/place/service/PlaceImageService.java, backend/src/main/java/com/daedan/festabook/place/service/PlaceService.java, backend/src/test/java/com/daedan/festabook/place/domain/PlaceAnnouncementFixture.java, backend/src/test/java/com/daedan/festabook/place/domain/PlaceFixture.java, backend/src/test/java/com/daedan/festabook/place/domain/PlaceImageFixture.java, backend/src/test/java/com/daedan/festabook/place/service/PlaceAnnouncementServiceTest.java, backend/src/test/java/com/daedan/festabook/place/service/PlaceImageServiceTest.java, backend/src/test/java/com/daedan/festabook/place/service/PlaceServiceTest.java
#5 
<br>
- 플레이스 전체 조회 API 구현
<br>
=> [BE] Place 생성 구현

backend/src/main/java/com/daedan/festabook/global/argumentresolver/OrganizationId.java, backend/src/main/java/com/daedan/festabook/global/argumentresolver/OrganizationIdArgumentResolver.java, backend/src/main/java/com/daedan/festabook/global/config/WebMvcConfig.java, backend/src/main/java/com/daedan/festabook/organization/infrastructure/OrganizationJpaRepository.java, backend/src/test/java/com/daedan/festabook/global/config/WebMvcConfigTest.java
#51
<br>
- OrganizationJpaRepository 추가, 설정 정보 organization.infrastructure에서 global로 이동
<br>
- 패키지 네이밍
=> [BE] OrganizationJpaRepository 추가, 설정 정보 global로 이동

backend/src/main/java/com/daedan/festabook/global/config/SwaggerConfig.java, backend/src/main/java/com/daedan/festabook/schedule/controller/ScheduleController.java
> #43 
<br>
- 일정 Swagger API 문서화를 추가했습니다.
- 추후 확장성을 대비해 Swagger 그룹화를 추가했습니다.
<br>
- 그룹화의 이름이 적절한 지 리뷰해주세요 :relaxed:
<br>
=> [BE] 일정 Swagger 및 그룹화 추가 

backend/src/main/java/com/daedan/festabook/announcement/controller/AnnouncementController.java, backend/src/main/java/com/daedan/festabook/announcement/domain/Announcement.java, backend/src/main/java/com/daedan/festabook/announcement/dto/AnnouncementResponses.java, backend/src/main/java/com/daedan/festabook/announcement/infrastructure/AnnouncementJpaRepository.java, backend/src/main/java/com/daedan/festabook/announcement/service/AnnouncementService.java, backend/src/main/java/com/daedan/festabook/organization/domain/Organization.java, backend/src/test/java/com/daedan/festabook/announcement/domain/AnnouncementFixture.java, backend/src/test/java/com/daedan/festabook/announcement/service/AnnouncementServiceTest.java
#29 
<br>
- 공지에 대학을 반영하여 수정
<br>
- 컨벤션 확인
=> [BE] 공지 대학 반영

backend/src/main/java/com/daedan/festabook/organization/domain/Organization.java, backend/src/main/java/com/daedan/festabook/schedule/controller/ScheduleController.java, backend/src/main/java/com/daedan/festabook/schedule/domain/EventDate.java, backend/src/main/java/com/daedan/festabook/schedule/infrastructure/EventDateJpaRepository.java, backend/src/main/java/com/daedan/festabook/schedule/service/ScheduleService.java, backend/src/test/java/com/daedan/festabook/organization/domain/OrganizationFixture.java, backend/src/test/java/com/daedan/festabook/schedule/domain/EventDateFixture.java, backend/src/test/java/com/daedan/festabook/schedule/service/ScheduleServiceTest.java
> #32 
<br>
- 일정 반환 API의 대학 Id 기반 탐색으로 변경했습니다.
- @soeun2537 미소와는 좀 다른 방식으로 구현해봤습니다. 내일 의논 후 결정해봅시다!
=> [BE] 일정 대학 반영

backend/src/main/java/com/daedan/festabook/global/config/SwaggerConfig.java, backend/src/main/resources/application.yml
> #56 
<br>
- Swagger 전역에 OrganizationId 추가했습니다.
- 새로 고침 이후에도 바뀌지 않도록 로컬 스토리지 사용하도록 설정 추가했습니다.
<br>
=> [BE] Swagger 전역 Organization Id 추가

backend/src/main/java/com/daedan/festabook/announcement/domain/Announcement.java, backend/src/main/java/com/daedan/festabook/announcement/dto/AnnouncementResponse.java, backend/src/test/java/com/daedan/festabook/announcement/domain/AnnouncementFixture.java
#57 
<br>
- 공지에 isPinned 필드 추가
=> [BE] 공지에 고정된 공지 여부를 추가

backend/src/main/java/com/daedan/festabook/place/controller/PlaceController.java, backend/src/test/java/com/daedan/festabook/orgnaization/domain/OrganizationFixture.java, backend/src/test/java/com/daedan/festabook/place/controller/PlaceControllerTest.java, backend/src/test/java/com/daedan/festabook/place/domain/PlaceAnnouncementFixture.java, backend/src/test/java/com/daedan/festabook/place/domain/PlaceFixture.java, backend/src/test/java/com/daedan/festabook/place/domain/PlaceImageFixture.java
#22
<br>
- 플레이스 인수테스트 작성
<br>
- 컨벤션 논의 필요한 부분
=> [BE] 플레이스 인수테스트 작성

backend/src/main/java/com/daedan/festabook/schedule/domain/Event.java, backend/src/main/java/com/daedan/festabook/schedule/dto/EventDateResponses.java, backend/src/main/java/com/daedan/festabook/schedule/service/ScheduleService.java, backend/src/test/java/com/daedan/festabook/global/config/WebMvcConfigTest.java, backend/src/test/java/com/daedan/festabook/schedule/controller/ScheduleControllerTest.java, backend/src/test/java/com/daedan/festabook/schedule/domain/EventDateFixture.java, backend/src/test/java/com/daedan/festabook/schedule/domain/EventFixture.java, backend/src/test/java/com/daedan/festabook/schedule/service/ScheduleServiceTest.java
> #20 
<br>
- 일정 인수테스트 작성했습니다.
- 이벤트 날짜 정렬 순서 비즈니스 로직을 추가했습니다.
<br>
- 인수테스트 작성 부분 집중해주세요!
=> [BE] 일정 인수테스트 작성

.github/workflows/ci-android.yml
> #64 
<br>
- 안드로이드 ci 설정했습니다.
- ktlint 검사를 하도록 설정했습니다.
<br>
- 나중에 base_url 과 같은 local.properties에 들어가는 값은 이제 깃허브 secret에 넣어두고 ci 실행 로그로 나오지 않게 해야해요.
=> [AN] Gitbub Action 를 활용한 CI 설정 추가

backend/src/main/java/com/daedan/festabook/global/exception/BusinessException.java, backend/src/main/java/com/daedan/festabook/global/exception/GlobalExceptionHandler.java, backend/src/test/java/com/daedan/festabook/global/exception/GlobalExceptionHandlerTest.java
#95 
<br>
- 전역 예외 핸들러를 추가하였습니다.
- 예외에 포함된 status code를 사용하고, message를 응답합니다.
<br>
- 테스트에 추가적으로 할 케이스가 있는지 궁금합니다.
<br>
=> [BE] 전역 예외 핸들러 추가

backend/src/main/resources/data.sql
> #97 
<br>
- 초기 테스트용 mock 데이터 추가했습니다.
<br>
- 자신 설계 Entity의 컬럼이 정상적으로 기입되었는 지 확인해주세요!
<br>
모든 Swagger 검증도 완료했습니다.
=> [BE] 테스트용 데이터 data.sql 추가

.github/workflows/ci-android.yml, android/build.gradle.kts, android/settings.gradle.kts
> #108 
<br>
- yml 파일 내 브랜치 명 변경
- clean project 속성 추가
- github secrets BASE_URL 값 생성
<br>
- Java 버전은 그대로 17로 일단 유지해두었습니다. 
<br>
=> [AN] 안드로이드 CI yml 파일 수정

.coderabbit.yaml
> #339 
<br>
- 충돌하는 부분을 수정했습니다.
=> [COMMON] 코드 레빗 충돌 수정

.github/workflows/slack-notify.yml
#311
<br>
- GitHub Noti 커스터마이징
<br>
- 적용 후 안드도 똑같이 적용 예정입니다~
<br>
=> [COMMON] GitHub Noti 커스터마이징

backend/src/main/java/com/daedan/festabook/place/controller/PlaceAnnouncementController.java, backend/src/main/java/com/daedan/festabook/place/dto/PlaceAnnouncementRequest.java, backend/src/main/java/com/daedan/festabook/place/infrastructure/PlaceAnnouncementJpaRepository.java, backend/src/main/java/com/daedan/festabook/place/service/PlaceAnnouncementService.java, backend/src/test/java/com/daedan/festabook/place/controller/PlaceAnnouncementControllerTest.java, backend/src/test/java/com/daedan/festabook/place/dto/PlaceAnnouncementRequestFixture.java, backend/src/test/java/com/daedan/festabook/place/service/PlaceAnnouncementServiceTest.java
#463 
<br>
- 플레이스 공지 생성 api 구현
<br>
=> [BE] 플레이스 공지 생성 api 구현

backend/src/main/java/com/daedan/festabook/place/controller/PlaceAnnouncementController.java, backend/src/main/java/com/daedan/festabook/place/domain/PlaceAnnouncement.java, backend/src/main/java/com/daedan/festabook/place/dto/PlaceAnnouncementUpdateRequest.java, backend/src/main/java/com/daedan/festabook/place/dto/PlaceAnnouncementUpdateResponse.java, backend/src/main/java/com/daedan/festabook/place/service/PlaceAnnouncementService.java, backend/src/test/java/com/daedan/festabook/place/controller/PlaceAnnouncementControllerTest.java, backend/src/test/java/com/daedan/festabook/place/domain/PlaceAnnouncementTest.java, backend/src/test/java/com/daedan/festabook/place/dto/PlaceAnnouncementUpdateRequestFixture.java, backend/src/test/java/com/daedan/festabook/place/service/PlaceAnnouncementServiceTest.java
#463 
<br>
- 플레이스 공지사항  수정 api 구현
<br>
=> [BE] 플레이스 공지사항 수정 api 구현

frontend/src/utils/api.js
#621 
<br>
- api-host를 env로 변경
=> [FE] api-host를 env로 변경

backend/src/main/java/com/daedan/festabook/council/dto/CouncilLoginResponse.java, backend/src/main/java/com/daedan/festabook/council/service/CouncilService.java, backend/src/test/java/com/daedan/festabook/council/controller/CouncilControllerTest.java, backend/src/test/java/com/daedan/festabook/council/service/CouncilServiceTest.java
#624
<br>
- festivalId 응답값 추가 Hotifx
<br>
=> [BE] festivalId 응답값 추가 Hotifx

frontend/src/auth/councilAuth.js
#623 
<br>
login response에 담겨서 오는 festivalId를 LocalStorage에 저장
<br>
=> [FE] login response에 담겨서 오는 festivalId를 LocalStorage에 저장

.github/workflows/backend-cd-dev.yml, .github/workflows/backend-cd-prod.yml
#644 
<br>
build할 때, sudo 권한 제공
=> [BE] build할 때, sudo 권한 제공

android/app/src/main/java/com/daedan/festabook/presentation/placeList/PlaceListChildViewModel.kt, android/app/src/main/java/com/daedan/festabook/presentation/placeList/PlaceListFragment.kt, android/app/src/main/java/com/daedan/festabook/presentation/placeList/model/PlaceListUiState.kt, android/app/src/main/java/com/daedan/festabook/presentation/placeList/placeMap/PlaceMapFragment.kt, android/app/src/main/java/com/daedan/festabook/util/FestabookGlobalExceptionHandler.kt, android/app/src/main/res/layout/fragment_place_list.xml, android/app/src/main/res/layout/item_place_list_skeleton.xml
> ex) #이슈번호, #이슈번호
<br>
- 구현한 기능을 작성해주세요.
<br>
- 특히 확인이 필요한 부분, 고민했던 부분 등을 적어주세요.
<br>
=> [AN] 공지 클릭 안되는 문제 및 이미지 로딩 전략 변경

frontend/src/App.jsx, frontend/src/components/modals/AddImageModal.jsx, frontend/src/pages/HomePage.jsx
> #714 
<br>
- 새로운 이미지 추가 안되는 버그 수정했습니다.
=> [FE] 새로운 이미지 추가 안되는 버그

.github/workflows/frontend-ci-cd-dev.yml
#748 
<br>
- 프론트엔드 스크립트 트리거 브랜치 변경 및 steps 하나로 변경
=> [FE] 프론트엔드 스크립트 트리거 브랜치 변경 및 steps 하나로 변경

android/app/build.gradle.kts
> #915 
<br>
- version name : v 1.1.0
- version code : 10100
<br>
- 특히 확인이 필요한 부분, 고민했던 부분 등을 적어주세요.
<br>
=> [AN] v 1.1.0 업데이트

.github/workflows/backend-ci.yml
#903 
<br>
- ci 트리거 branch backend-dev/prod로 변경
<br>
=> [BE] ci 트리거 branch backend-dev/prod로 변경

frontend/src/pages/PlacePage.jsx
#942 
<br>
- 플레이스 추가 버튼을 각 카테고리에서 할 수 있게 추가
<br>
=> [FE] 플레이스 추가 버튼을 각 카테고리에서 할 수 있게 추가

frontend/src/pages/PlacePage.jsx
#946 
<br>
- 운영 주체도 검색 범위에 포함하도록 변경
<br>
=> [FE] 운영 주체도 검색 범위에 포함

frontend/index.html, frontend/public/robots.txt
#998 
<br>
- robots.txt 추가
```
// 모든 검색엔진에게
User-agent: *
// 모든 페이지를 수집하지 마라고 알린다.
Disallow: /
```
- index.html에 수집을 막는 meta tag 추가
- https://happylie.tistory.com/195
```html
<meta name="robots" content="noindex, nofollow, noarchive">
```
- 응답 헤더에도 아래처럼 추가할 예정
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/X-Robots-Tag
<br>
- 특히 확인이 필요한 부분, 고민했던 부분 등을 적어주세요.
<br>
=> [FE] 학생회 페이지의 검색엔진 노출을 방지
